<center><h1>Container Types</h1></center>
<center><h3>Paul Stey</h3></center>
<center><h3>2021-09-21</h3></center>

# 1. Container Types

  - What is a container type?
  - Examples: 
    + `vector`
    + `matrix`
    + `array`
    + `list`

# 2. The `vector` Type

The `vector` type in R is a one-dimensional array that can hold homogeneous data (i.e., data that is all of the same type).

In [5]:
my_vec <- c(42, 137, 34)             # use c() function to combine elements in to vector

print(my_vec)                       # Note: all elements are of type integer

[1]  42 137  34


In [6]:
animal_vec <- c("dog", "cat", "bird", "potato")

print(animal_vec)

[1] "dog"    "cat"    "bird"   "potato"


## 2.1 Accessing Elements (i.e., "indexing")

 - Once we have a vector, we need to be able to access its elements
 - This is done using the `[]` notation.

In [7]:
people <- c("ned", "jon", "robb", "arya")

In [18]:
people[1]                  # use [] notation to access element

[1] "jon"  "robb" "arya"

### 2.1.1 Range-Based Indexing

 - We often want more than a single element from a vector
 - Range-based intexing is one method of getting "slices" of a vector (i.e., contiguous elements)

In [21]:
print(people)                 # Use vector from previous example

people[1:3]                   # use range notation to get "slice"

[1] "ned"  "jon"  "robb" "arya"


[1] "ned"  "jon"  "robb"

## 2.2 Indexing with Vector

 - Suppose we want a non-contiguous set of elements
 - We can use a vector of integers for indexing

In [24]:
vec_idx <- c(1, 4)

people[vec_idx]

[1] "ned"  "arya"

In [25]:
people[c(1, 3)]

[1] "ned"  "robb"

## 2.3 Indexing with Booleans

  - We are also able to use boolean values to index

In [26]:
print(people) 

[1] "ned"  "jon"  "robb" "arya"


In [27]:
is_stark <- c(TRUE, FALSE, TRUE, TRUE)

people[is_stark]

[1] "ned"  "robb" "arya"

## 2.4 Modifying Elements

 - We can use indexing or slicing to modify a vector's elements

In [31]:
animal_vec <- c("dog", "cat", "bird", "potato")

print(animal_vec)

[1] "dog"    "cat"    "bird"   "potato"


In [33]:
animal_vec[4] <- "fish"          # this is a note to my future self
 
print(animal_vec)                # potato is an animal

[1] "dog"  "cat"  "bird" "fish"


# 3. The `matrix` Type

  - 2-dimensional array (i.e., height and width)
  - Store homogeneous data (i.e., all same type)

In [41]:
dat <- 1:12                 # generate sequence from 1 to 12

m <- matrix(dat, nrow = 3)  # put `dat` in to a matrix

In [42]:
print(m)

     [,1] [,2] [,3] [,4]
[1,]    1    4    7   10
[2,]    2    5    8   11
[3,]    3    6    9   12



## 3.1 Non-Numeric Data

 - Like the `vector` type, we can also store non-numeric data in a `matrix`

In [43]:
some_names <- c("lee", "sue", "bill", "don")

name_mat <- matrix(some_names, nrow = 2)

In [44]:
print(name_mat)

     [,1]  [,2]  
[1,] "lee" "bill"
[2,] "sue" "don" 


## 3.2 Indexing `matrix` Object

 - Indexing and slicing work much like in `vector` objects

In [45]:
x <- matrix(rnorm(8), nrow = 4)

print(x)

           [,1]       [,2]
[1,] 0.01689109 -1.3767263
[2,] 0.78709777 -0.9585521
[3,] 0.91263068  1.6350832
[4,] 0.70633089 -1.5212946


In [46]:
x[1, 2]                       # element in first row, second column

[1] -1.376726

In [47]:
x[3, 2]                       # third row, second column

[1] 1.635083

### 3.2.1 Getting a "slice"

 - Can also using indexing to get an entire row or column

In [48]:
w <- matrix(1:12, nrow = 4)

print(w)

     [,1] [,2] [,3]
[1,]    1    5    9
[2,]    2    6   10
[3,]    3    7   11
[4,]    4    8   12


In [49]:
w[2, ]                        # get second row

[1]  2  6 10

In [50]:
w[, 1]                        # get first column

[1] 1 2 3 4

### 3.2.2 Matrix Slicing (cont.)

In [51]:
row_idx <- c(2, 4)
col_idx <- 3

w[row_idx, col_idx]           

[1] 10 12